### ISSUE TITLE
google.cloud.gcp_dns_resource_record_set does not correctly manage MX records

### ISSUE THREAD

**Issue by huang-jy** [ansible-collections/google.cloud#472]
##### SUMMARY
When trying to create a new MX record into an existing managed zone, Ansible falls over with a messy stacktrace. The example provided on the document, does, however, work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
google.cloud.gcp_dns_resource_record_set

##### ANSIBLE VERSION
```
ansible [core 2.11.6] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/johnny/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/johnny/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.1 (main, Dec  7 2021, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```
$ ansible-galaxy collection list

# /usr/share/ansible/collections/ansible_collections
Collection           Version
-------------------- -------
ansible.netcommon    2.2.0  
ansible.posix        1.2.0  
ansible.utils        2.3.0  
community.general    3.8.2  
community.kubernetes 1.1.1  
google.cloud         1.0.1  

# /home/johnny/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
ansible.netcommon    2.5.0  
ansible.posix        1.3.0  
ansible.utils        2.4.3  
community.general    4.1.0  
community.kubernetes 2.0.1  
google.cloud         1.0.2  
kubernetes.core      2.2.2  
```

##### CONFIGURATION
```
{no output from command}
```

##### OS / ENVIRONMENT

Fedora 35

##### STEPS TO REPRODUCE
Run as following (will need to set `project` variable and `ansible-user.json` serviceaccount file accordingly)
```yaml
- name: create a managed zone
  google.cloud.gcp_dns_managed_zone:
    name: test-managed=zone
    dns_name: example.co.uk.
    description: ""
    project: "{{ project }}"
    auth_kind: serviceaccount
    service_account_file: "ansible-user.json"
    state: present
  register: managed_zone_register

- name: create a resource record set
  google.cloud.gcp_dns_resource_record_set:
    name: a-example.example.co.uk.
    managed_zone: "{{ managed_zone_register }}"
    type: A
    ttl: 600
    target:
    - 10.1.2.3
    - 40.5.6.7
    project: "{{ project }}"
    auth_kind: serviceaccount
    service_account_file: "ansible-user.json"
    state: present

- name: create a resource record set
  google.cloud.gcp_dns_resource_record_set:
    name: b-example.example.co.uk.
    managed_zone: "{{ managed_zone_register }}"
    type: MX
    ttl: 600
    target:
    - 10.1.2.3
    - 40.5.6.7
    project: "{{ project }}"
    auth_kind: serviceaccount
    service_account_file: "ansible-user.json"
    state: present
```

##### EXPECTED RESULTS

An A record and an MX record to be created

##### ACTUAL RESULTS

The first record set created, the second failed, with `requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://dns.googleapis.com/dns/v1/projects/{project-name}/managedZones/{managed-zone-name}/changes`

But no indicator as to what was bad about it...

Full output (redacted):

```
TASK [test-dns : create a resource record set] ********************************************************************************************************************************************
task path: /home/johnny/work/repos/gke-ansible/roles/test-dns/tasks/main.yaml:26
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: johnny
<localhost> EXEC /bin/sh -c 'echo ~johnny && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johnny/.ansible/tmp `"&& mkdir "` echo /home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582 `" && echo ansible-tmp-1640169712.2579455-98249-74229942119582="` echo /home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582 `" ) && sleep 0'
Using module file /home/johnny/.ansible/collections/ansible_collections/google/cloud/plugins/modules/gcp_dns_resource_record_set.py
<localhost> PUT /home/johnny/.ansible/tmp/ansible-local-97857lfajtxys/tmpf6_i68dt TO /home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582/AnsiballZ_gcp_dns_resource_record_set.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582/ /home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582/AnsiballZ_gcp_dns_resource_record_set.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582/AnsiballZ_gcp_dns_resource_record_set.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582/AnsiballZ_gcp_dns_resource_record_set.py", line 100, in <module>
    _ansiballz_main()
  File "/home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582/AnsiballZ_gcp_dns_resource_record_set.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582/AnsiballZ_gcp_dns_resource_record_set.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.google.cloud.plugins.modules.gcp_dns_resource_record_set', init_globals=dict(_module_fqn='ansible_collections.google.cloud.plugins.modules.gcp_dns_resource_record_set', _modlib_path=modlib_path),
  File "/usr/lib64/python3.10/runpy.py", line 209, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_google.cloud.gcp_dns_resource_record_set_payload_ux9wn9vo/ansible_google.cloud.gcp_dns_resource_record_set_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_dns_resource_record_set.py", line 498, in <module>
  File "/tmp/ansible_google.cloud.gcp_dns_resource_record_set_payload_ux9wn9vo/ansible_google.cloud.gcp_dns_resource_record_set_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_dns_resource_record_set.py", line 234, in main
  File "/tmp/ansible_google.cloud.gcp_dns_resource_record_set_payload_ux9wn9vo/ansible_google.cloud.gcp_dns_resource_record_set_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_dns_resource_record_set.py", line 245, in create
  File "/tmp/ansible_google.cloud.gcp_dns_resource_record_set_payload_ux9wn9vo/ansible_google.cloud.gcp_dns_resource_record_set_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_dns_resource_record_set.py", line 418, in create_change
  File "/tmp/ansible_google.cloud.gcp_dns_resource_record_set_payload_ux9wn9vo/ansible_google.cloud.gcp_dns_resource_record_set_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_dns_resource_record_set.py", line 486, in return_if_change_object
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://dns.googleapis.com/dns/v1/projects/{project}/managedZones/{managed-zone}/changes
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582/AnsiballZ_gcp_dns_resource_record_set.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582/AnsiballZ_gcp_dns_resource_record_set.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/johnny/.ansible/tmp/ansible-tmp-1640169712.2579455-98249-74229942119582/AnsiballZ_gcp_dns_resource_record_set.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.google.cloud.plugins.modules.gcp_dns_resource_record_set', init_globals=dict(_module_fqn='ansible_collections.google.cloud.plugins.modules.gcp_dns_resource_record_set', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.10/runpy.py\", line 209, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_google.cloud.gcp_dns_resource_record_set_payload_ux9wn9vo/ansible_google.cloud.gcp_dns_resource_record_set_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_dns_resource_record_set.py\", line 498, in <module>\n  File \"/tmp/ansible_google.cloud.gcp_dns_resource_record_set_payload_ux9wn9vo/ansible_google.cloud.gcp_dns_resource_record_set_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_dns_resource_record_set.py\", line 234, in main\n  File \"/tmp/ansible_google.cloud.gcp_dns_resource_record_set_payload_ux9wn9vo/ansible_google.cloud.gcp_dns_resource_record_set_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_dns_resource_record_set.py\", line 245, in create\n  File \"/tmp/ansible_google.cloud.gcp_dns_resource_record_set_payload_ux9wn9vo/ansible_google.cloud.gcp_dns_resource_record_set_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_dns_resource_record_set.py\", line 418, in create_change\n  File \"/tmp/ansible_google.cloud.gcp_dns_resource_record_set_payload_ux9wn9vo/ansible_google.cloud.gcp_dns_resource_record_set_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_dns_resource_record_set.py\", line 486, in return_if_change_object\n  File \"/usr/lib/python3.10/site-packages/requests/models.py\", line 953, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://dns.googleapis.com/dns/v1/projects/{project}/managedZones/{managed-zone}/changes\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by huang-jy** [comment]
Figured it out eventually, the target block needed to formatted like this:

```
    target:
    - "10 mail.host.org."
    - "10 mail2.host.org."
```

And needed the trailing dot.
