### ISSUE TITLE
gcp_compute_instance_info does not use default service_account_email with auth_kind of machineaccount

### ISSUE THREAD

**Issue by lachlanmulcahy** [ansible-collections/google.cloud#568]
##### SUMMARY

The docs for gcp_compute_instance_info state that the 'service_account_email' parameter is:

"An optional service account email address if machineaccount is selected and the user does not wish to use the default email."

If a user provides auth_kind of `machineaccount` and does not specify the `service_account_email` parameter, the ansible task will fail with an error that appears to be related to it not correctly looking up the `default` service account for the host. 

Explicitly providing the value of "default" to `service_account_email` results in it using the default service account for the VM as expected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_instance_info

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.3]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.7 (main, Mar 10 2023, 10:47:39) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /root/.ansible/collections/ansible_collections
Collection   Version
------------ -------
google.cloud 1.1.3

# /usr/local/lib/python3.10/dist-packages/ansible_collections
Collection   Version
------------ -------
google.cloud 1.1.2
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

Ubuntu 22.10

##### STEPS TO REPRODUCE

Create a Google Compute VM with a default service account.
Connect to the VM and validate that the following returns the service account as expected:

`curl -H 'Metadata-Flavor:Google' 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email'`

Run the example playbook and observe the error.

```yaml
     - name: get info on an instance
        gcp_compute_instance_info:
          filters:
          - name = dummyhost 
          zone: us-central1-f
          project: default
          auth_kind: machineaccount
        register: gcp_info

```

##### EXPECTED RESULTS

I'd expect this to be able to utilize the email of the default serviceaccount associated with the current VM for the purpose of authenticating with Google services.

I would expect for this dummy example, an HTTP 403 error from the module telling me permission denied OR a 404 error because "dummyhost" doesn't exist in `us-central1-f` - we just made it up.

##### ACTUAL RESULTS

It appears rather than using the string 'default' to look up the email for the default service account of the machine, that the code is getting a Python variable that has been set to `None` and translating that into the string "None" when it forms the URL to use to retrieve the email of the serviceaccount in question.

This is the URL that it seems to be trying to incorrectly call that suggests this to me:
`http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/None/?recursive=true`

If you explicitly provide the string "default" as the `service_account_email` parameter, this module functions as expected.

```paste below
TASK [get info on an instance] *************************************************
task path: /opt/lacework/postboot/rp-gcp.yml:11
redirecting (type: modules) ansible.builtin.gcp_compute_instance_info to google.cloud.gcp_compute_instance_info
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062 `" && echo ansible-tmp-1680137847.4975257-41710-55623911957062="` echo /root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.gcp_compute_instance_info to google.cloud.gcp_compute_instance_info
Using module file /root/.ansible/collections/ansible_collections/google/cloud/plugins/modules/gcp_compute_instance_info.py
<localhost> PUT /root/.ansible/tmp/ansible-local-41592xkp3qdnu/tmpbjuc87_3 TO /root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062/AnsiballZ_gcp_compute_instance_info.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062/ /root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062/AnsiballZ_gcp_compute_instance_info.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062/AnsiballZ_gcp_compute_instance_info.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 111, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 87, in _retrieve_info
    info = _metadata.get_service_account_info(
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 234, in get_service_account_info
    return get(request, path, params={"recursive": "true"})
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 182, in get
    raise exceptions.TransportError(
google.auth.exceptions.TransportError: ('Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/None/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb\'<!DOCTYPE html>\\n<html lang=en>\\n  <meta charset=utf-8>\\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\\n  <title>Error 404 (Not Found)!!1</title>\\n  <style>\\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\\n  </style>\\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\\n  <p><b>404.</b> <ins>That\\xe2\\x80\\x99s an error.</ins>\\n  <p>The requested URL <code>/computeMetadata/v1/instance/service-accounts/None/?recursive=true</code> was not found on this server.  <ins>That\\xe2\\x80\\x99s all we know.</ins>\\n\'', <google.auth.transport.requests._Response object at 0x7f458ffff040>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062/AnsiballZ_gcp_compute_instance_info.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062/AnsiballZ_gcp_compute_instance_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062/AnsiballZ_gcp_compute_instance_info.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.google.cloud.plugins.modules.gcp_compute_instance_info', init_globals=dict(_module_fqn='ansible_collections.google.cloud.plugins.modules.gcp_compute_instance_info', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_gcp_compute_instance_info_payload_jitn9nvq/ansible_gcp_compute_instance_info_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_compute_instance_info.py", line 685, in <module>
  File "/tmp/ansible_gcp_compute_instance_info_payload_jitn9nvq/ansible_gcp_compute_instance_info_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_compute_instance_info.py", line 625, in main
  File "/tmp/ansible_gcp_compute_instance_info_payload_jitn9nvq/ansible_gcp_compute_instance_info_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_compute_instance_info.py", line 640, in fetch_list
  File "/tmp/ansible_gcp_compute_instance_info_payload_jitn9nvq/ansible_gcp_compute_instance_info_payload.zip/ansible_collections/google/cloud/plugins/module_utils/gcp_utils.py", line 135, in list
  File "/tmp/ansible_gcp_compute_instance_info_payload_jitn9nvq/ansible_gcp_compute_instance_info_payload.zip/ansible_collections/google/cloud/plugins/module_utils/gcp_utils.py", line 152, in full_get
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/transport/requests.py", line 545, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/credentials.py", line 135, in before_request
    self.refresh(request)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 117, in refresh
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.RefreshError: ('Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/None/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb\'<!DOCTYPE html>\\n<html lang=en>\\n  <meta charset=utf-8>\\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\\n  <title>Error 404 (Not Found)!!1</title>\\n  <style>\\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\\n  </style>\\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\\n  <p><b>404.</b> <ins>That\\xe2\\x80\\x99s an error.</ins>\\n  <p>The requested URL <code>/computeMetadata/v1/instance/service-accounts/None/?recursive=true</code> was not found on this server.  <ins>That\\xe2\\x80\\x99s all we know.</ins>\\n\'', <google.auth.transport.requests._Response object at 0x7f458ffff040>)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n    self._retrieve_info(request)\n  File \"/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py\", line 87, in _retrieve_info\n    info = _metadata.get_service_account_info(\n  File \"/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n    return get(request, path, params={\"recursive\": \"true\"})\n  File \"/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py\", line 182, in get\n    raise exceptions.TransportError(\ngoogle.auth.exceptions.TransportError: ('Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/None/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\\nb\\'<!DOCTYPE html>\\\\n<html lang=en>\\\\n  <meta charset=utf-8>\\\\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\\\\n  <title>Error 404 (Not Found)!!1</title>\\\\n  <style>\\\\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\\\\n  </style>\\\\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\\\\n  <p><b>404.</b> <ins>That\\\\xe2\\\\x80\\\\x99s an error.</ins>\\\\n  <p>The requested URL <code>/computeMetadata/v1/instance/service-accounts/None/?recursive=true</code> was not found on this server.  <ins>That\\\\xe2\\\\x80\\\\x99s all we know.</ins>\\\\n\\'', <google.auth.transport.requests._Response object at 0x7f458ffff040>)\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062/AnsiballZ_gcp_compute_instance_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062/AnsiballZ_gcp_compute_instance_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1680137847.4975257-41710-55623911957062/AnsiballZ_gcp_compute_instance_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.google.cloud.plugins.modules.gcp_compute_instance_info', init_globals=dict(_module_fqn='ansible_collections.google.cloud.plugins.modules.gcp_compute_instance_info', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_gcp_compute_instance_info_payload_jitn9nvq/ansible_gcp_compute_instance_info_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_compute_instance_info.py\", line 685, in <module>\n  File \"/tmp/ansible_gcp_compute_instance_info_payload_jitn9nvq/ansible_gcp_compute_instance_info_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_compute_instance_info.py\", line 625, in main\n  File \"/tmp/ansible_gcp_compute_instance_info_payload_jitn9nvq/ansible_gcp_compute_instance_info_payload.zip/ansible_collections/google/cloud/plugins/modules/gcp_compute_instance_info.py\", line 640, in fetch_list\n  File \"/tmp/ansible_gcp_compute_instance_info_payload_jitn9nvq/ansible_gcp_compute_instance_info_payload.zip/ansible_collections/google/cloud/plugins/module_utils/gcp_utils.py\", line 135, in list\n  File \"/tmp/ansible_gcp_compute_instance_info_payload_jitn9nvq/ansible_gcp_compute_instance_info_payload.zip/ansible_collections/google/cloud/plugins/module_utils/gcp_utils.py\", line 152, in full_get\n  File \"/usr/lib/python3/dist-packages/requests/sessions.py\", line 542, in get\n    return self.request('GET', url, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/google/auth/transport/requests.py\", line 545, in request\n    self.credentials.before_request(auth_request, method, url, request_headers)\n  File \"/usr/local/lib/python3.10/dist-packages/google/auth/credentials.py\", line 135, in before_request\n    self.refresh(request)\n  File \"/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n    six.raise_from(new_exc, caught_exc)\n  File \"<string>\", line 3, in raise_from\ngoogle.auth.exceptions.RefreshError: ('Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/None/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\\nb\\'<!DOCTYPE html>\\\\n<html lang=en>\\\\n  <meta charset=utf-8>\\\\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\\\\n  <title>Error 404 (Not Found)!!1</title>\\\\n  <style>\\\\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\\\\n  </style>\\\\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\\\\n  <p><b>404.</b> <ins>That\\\\xe2\\\\x80\\\\x99s an error.</ins>\\\\n  <p>The requested URL <code>/computeMetadata/v1/instance/service-accounts/None/?recursive=true</code> was not found on this server.  <ins>That\\\\xe2\\\\x80\\\\x99s all we know.</ins>\\\\n\\'', <google.auth.transport.requests._Response object at 0x7f458ffff040>)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by toumorokoshi** [comment]
Thanks for the report! I kind of feel like in this cause it might be better to just fix the documentation and always require `service_account_email` as the parameter? since it'll be more explicit as to the intention of the user.

The fact that it's mapped directly to the URL (and therefore somewhat easier to reason what the code is doing) is an added benefit, IMO.

**Comment by sjshuck** [comment]
Personally I think the documentation should stay the same, and instead of erroring when `service_account_email` is unset, it should do what's promised.  This also mirrors the behavior of the [underlying Python API](https://googleapis.dev/python/google-auth/latest/reference/google.auth.compute_engine.html#google.auth.compute_engine.Credentials).
